/templates:
  bagread_node:
    ros__parameters:
      bagfile: "/media/external/ATR/bags/Vegas_2021/objects/2022-10-27-1949_TEXAS_run1_vehicle" #"/home/stephanie/Downloads/vegas_snipit_3"
      topics_to_record: "/raptor_dbw_interface/wheel_speed_report /joystick/brake_cmd_override /joystick/accelerator_cmd_max /luminar_left_points"
      # topics_to_record: "/joystick/accelerator_cmd_max"
      # topics_to_record: "/luminar_left_points"
      timer_ms: 100